version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=nestjs_store
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=PostgresDbPassword
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=edward.trigos@nivelics.co
      - PGADMIN_DEFAULT_PASSWORD=PgAdminPassword
    ports:
      - '5050:80'
    depends_on:
      - postgres

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=nestjs_store
      - MYSQL_ROOT_PASSWORD=MysqlDbPassword
    ports:
      - '3307:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=MysqlDbPassword
      - PMA_HOST=mysql
    ports:
      - '8080:80'
    depends_on:
      - mysql
